#### Marco Aurélio Souza
#### Paulo R. K. Nakaima
#### Rodrigo R. Veras

### Hill-Climbing n-Queens

Hill-Climbing é uma técnica de otimização matemática que pertence ao grupo das buscas locais. Ele é um algoritmo
iterativo que inicia com uma solução arbitrária para um dado problema e, em seguida, tenta achar uma solução melhor fazendo alterações incrementais no problema.

### Condições iniciais

Como ponto de partida implementamos o algoritmo Hill-Climbing (Subida da encosta) utilizando a heurística de pares de damas atacadas. Este trabalho seguiu a solução proposta no livro de Norvig e Russel, onde a condição de existência da configuração inicial do tabuleiro é duas ou mais rainhas não devem estar em uma mesma coluna ao mesmo tempo. Ainda assim, cada rainha so poderá se movimentada dentro de sua coluna inicial.

#### heurística

A herística é baseada na quantidade de pares de rainhas atacante no estado corrente do jogo. No algorítmo, é somado a quantidade desses pares no total para cada estado corrente. As rainhas são movimentadas apenas nas linhas dentro de suas respectivas colunas de origem. Veja os passo a seguir:

1. Dado um estado inicial, é selecionado a rainha da primeira coluna;
2. É, então, calculado a quantidade de pares atacantes no total (em todo o tabuleiro) para cada nova posição assumida por essa rainha na coluna dada;
3. A posição que resultou no menor valor total de rainhas atacantes (valor da heurística) é assumida como nova posição para esta rainha;
4. Os passos anteriores são repetidos para todas as colunas sucessivas;
5. Enquanto o valor total de rainhas atacantes não for zero (estado objetivo), esses passos são repetidos, passando novamente por todas as colunas.


### Desenvolvimento

Testamos com a configuração do tabuleiro utilizada como exemplo no livro de Norvig e Russel:

In [1]:
from board.board import Board

n = 8
board = Board(n)

i, j = 4, 0
board[i, j] = 1
i, j = 5, 1
board[i, j] = 1
i, j = 6, 2
board[i, j] = 1
i, j = 3, 3
board[i, j] = 1
i, j = 4, 4
board[i, j] = 1
i, j = 5, 5
board[i, j] = 1
i, j = 6, 6
board[i, j] = 1
i, j = 5, 7
board[i, j] = 1
board.print()

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 1 0 0 0]
 [0 1 0 0 0 1 0 1]
 [0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]]


Nesta configuração o mínimo de estados necessários é 5. Abaixo está o gráfico da topologia de um dos experimentos executados, o qual encontra a solução passando por 9 estados:

![landscape-graph](figures/russel-norvig-example.png)

Outro experimento no qual o algoritmo fica preso por um longo tempo em uma planíce (shoulder), isto é, vários sucessores com o mesmo valor mas com uma saída encosta acima:
![landscape-graph](figures/russel-norvig-example-shoulder.png)

Os gráficos a seguir são experimentos executados com inicialização randômica do tabuleiro:

In [12]:
'''
inicio 

[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 1]
 [0 0 0 0 0 0 1 0]]

solução

[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]]
 '''

'\ninicio \n\n[[0 0 1 0 0 0 0 0]\n [0 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 0]\n [0 0 0 0 0 1 0 0]\n [0 0 0 0 1 0 0 0]\n [1 0 0 0 0 0 0 0]\n [0 1 0 1 0 0 0 1]\n [0 0 0 0 0 0 1 0]]\n\nsolução\n\n[[0 0 1 0 0 0 0 0]\n [0 0 0 0 0 1 0 0]\n [0 1 0 0 0 0 0 0]\n [0 0 0 0 1 0 0 0]\n [0 0 0 0 0 0 0 1]\n [1 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 1 0]\n [0 0 0 1 0 0 0 0]]\n '

![landscape-graph](figures/10-experiment.png)

In [1]:
'''
Início: 


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 1]
 [0 1 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]]

Solução:
[[0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]]


'''

'\nInício: \n\n\n[[0 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 0]\n [1 0 0 0 0 1 0 0]\n [0 0 0 0 1 0 0 1]\n [0 1 1 0 0 0 0 0]\n [0 0 0 1 0 0 0 0]\n [0 0 0 0 0 0 1 0]]\n\nSolução:\n[[0 0 0 0 1 0 0 0]\n [0 0 1 0 0 0 0 0]\n [1 0 0 0 0 0 0 0]\n [0 0 0 0 0 1 0 0]\n [0 0 0 0 0 0 0 1]\n [0 1 0 0 0 0 0 0]\n [0 0 0 1 0 0 0 0]\n [0 0 0 0 0 0 1 0]]\n\n\n'

![landscape-graph](figures/15-experiment.png)

In [2]:
'''
Início:


[[0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1]
 [1 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0]]

Solução:

[[0 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0]]

'''

'\nInício:\n\n\n[[0 0 0 1 0 0 1 0]\n [0 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 0]\n [0 1 0 0 0 0 0 0]\n [0 0 0 0 0 1 0 1]\n [1 0 1 0 0 0 0 0]\n [0 0 0 0 1 0 0 0]\n [0 0 0 0 0 0 0 0]]\n\nSolução:\n\n[[0 0 0 1 0 0 0 0]\n [0 1 0 0 0 0 0 0]\n [0 0 0 0 0 0 1 0]\n [0 0 1 0 0 0 0 0]\n [0 0 0 0 0 1 0 0]\n [0 0 0 0 0 0 0 1]\n [0 0 0 0 1 0 0 0]\n [1 0 0 0 0 0 0 0]]\n\n'

![landscape-graph](figures/16-experiment.png)

In [3]:
'''
Inicio:

[[0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0]
 [0 0 0 1 0 0 1 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]]

Solução:

[[0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0]]

'''

'\nInicio:\n\n[[0 0 0 0 0 0 0 0]\n [0 0 1 0 0 0 0 0]\n [0 0 0 0 0 0 0 0]\n [0 0 0 0 1 1 0 0]\n [0 0 0 1 0 0 1 0]\n [0 0 0 0 0 0 0 1]\n [1 0 0 0 0 0 0 0]\n [0 1 0 0 0 0 0 0]]\n\nSolução:\n\n[[0 0 0 0 0 1 0 0]\n [0 0 1 0 0 0 0 0]\n [0 0 0 0 0 0 1 0]\n [0 0 0 1 0 0 0 0]\n [1 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 1]\n [0 1 0 0 0 0 0 0]\n [0 0 0 0 1 0 0 0]]\n\n'

![landscape-graph](figures/17-experiment.png)

In [4]:
'''
Início:


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 1 1 0 1]
 [1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


Solução:

[[0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]]

'''

'\nInício:\n\n\n[[0 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 0]\n [0 0 1 1 0 0 0 0]\n [0 0 0 0 0 0 0 0]\n [0 1 0 0 1 1 0 1]\n [1 0 0 0 0 0 1 0]\n [0 0 0 0 0 0 0 0]\n [0 0 0 0 0 0 0 0]]\n\n\nSolução:\n\n[[0 0 1 0 0 0 0 0]\n [0 0 0 0 0 1 0 0]\n [0 0 0 0 0 0 0 1]\n [1 0 0 0 0 0 0 0]\n [0 0 0 1 0 0 0 0]\n [0 0 0 0 0 0 1 0]\n [0 0 0 0 1 0 0 0]\n [0 1 0 0 0 0 0 0]]\n\n'

![landscape-graph](figures/18-experiment.png)

### Resultados

Foram realizados alguns experimentos, no entanto, não foi encontrado uma configuração onde o algoritmo ficasse preso permanentemente em alguma colina que não fosse a melhor. O que não significa que não exista um.

Conforme dito anteriormente, o algorítmo inicializa um tabuleiro de tamanho N, cujo valor é atribuído no código antes da execução. O algorítmo foi validado com o tabuleiro de N = 8. Também foram testados com valores maiores que 8.

Como não foi possível gerar uma configuração inicial do tabuleiro na qual exista um platô utilizamos o exemplo apresentado no livro de Russel e Norvig. Nesta configuração qualquer movimento possui o valor maior que 1, portanto o algoritmo de subida da ecosta fica preso em um platô.

In [2]:
'''
Início:

[[0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
 
 '''

'\nInício:\n\n[[0 0 0 0 0 0 1 0]\n [0 0 0 0 1 0 0 0]\n [0 1 0 0 0 0 0 0]\n [0 0 0 1 0 0 0 0]\n [0 0 0 0 0 1 0 0]\n [0 0 0 0 0 0 0 1]\n [0 0 1 0 0 0 0 0]\n [1 0 0 0 0 0 0 0]]\n \n '

![landscape-graph](figures/21-experiment.png)

Desse modo uma das alternativas é fazer com que o algoritmo 'perceba' que está preso em um loop infinito. E escolher um movimento que piore a heurística mas que possivelmente encontra uma solução.

A estratégia adotada neste trabalho foi contar as iterações em que um dado valor se repete até um limiar de 100. Após isto assumi-se que o algoritmo está preso em um platô. Em seguida, é reiniciado o tabuleiro com posições aleatórias.

In [3]:
'''
Início:
[[0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]

Solução:
[[0 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0 0]]
 '''

'\nInício:\n[[0 0 0 0 0 0 1 0]\n [0 0 0 0 1 0 0 0]\n [0 1 0 0 0 0 0 0]\n [0 0 0 1 0 0 0 0]\n [0 0 0 0 0 1 0 0]\n [0 0 0 0 0 0 0 1]\n [0 0 1 0 0 0 0 0]\n [1 0 0 0 0 0 0 0]]\n\nSolução:\n[[0 0 0 0 0 1 0 0]\n [0 1 0 0 0 0 0 0]\n [0 0 0 0 0 0 1 0]\n [1 0 0 0 0 0 0 0]\n [0 0 0 1 0 0 0 0]\n [0 0 0 0 0 0 0 1]\n [0 0 0 0 1 0 0 0]\n [0 0 1 0 0 0 0 0]]\n '

![landscape-graph](figures/23-experiment.png)

O código da subida da encosta em sua versão final:

In [4]:
import numpy as np
from numpy.random import randint as rand

QUEEN = 1
H = 2

class HillClimbing:
  
  def __init__(self,board):
    self._board = board
    self._N = board.getN()
    self._current_node = self._make_node()
  
  def _heuristic(self):
    rv = dv = 0
    rv = self._board.count_atack_row()
    dv = self._board.count_main_diagonal()
    dv += self._board.count_secondary_diagonal()
    return int(rv + dv)

  def _make_node(self):
    i, j = self._board.find_queen(rand(8))
    return [i, j, self._heuristic()]

  def _find_best_value(self):
    best_values = [[self._current_node[0], self._current_node[1], self._current_node[H]]]
    for column in range(self._N):
      for row in range(self._N):
        i, j = self._board.move_queen(row, column)
        neighbor = [row, column, self._heuristic()]
        self._board.move_queen(i, j)

        if best_values[0][H] == neighbor[H]:
          best_values.append(neighbor)
        
        if best_values[0][H] > neighbor[H]:
          best_values.clear()
          best_values.append(neighbor)
    
    nbr_same_value = len(best_values)
    if nbr_same_value != 0:
      return best_values[rand(nbr_same_value)]
    return best_values[0]
  
  def get_board(self):
    return self._board.get_board()

  def execute(self):
    yield self._current_node[H]
    step = 0
    last_value = [self._current_node[0], self._current_node[1], self._current_node[H]]
    while True:
      h = self._find_best_value()
      last_value[0] = h[0]
      last_value[1] = h[1]
      last_value[H] = h[H]
      if self._current_node[H] >= h[H]:
        self._current_node = h
        self._board.move_queen(h[0], h[1])
        yield h[H]
      if self._current_node[H] == 0:
        self._board.print()
        break
      if last_value[H] == h[H]:
        step += 1
      if step == 100:
        step = 0
        self._board.rand_init()
        i, j = self._board.find_queen(0)
        self._current_node = [i, j, self._heuristic()]
